import * as React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Search, Volume2, X } from 'lucide-react';
import { ChapterCard } from '../../components/primitives/ChapterCard';
import { EmptyState } from '../../components/primitives/EmptyState';
import { Button } from '../../components/ui/button';
import { cn } from '../../lib/utils';

interface CardItem {
  id: string;
  type: string;
  article?: string;
  word: string;
  english: string;
  hindi: string;
  exampleSentences?: { id: string; sentenceDe: string; sentenceEn: string; autoGenerated: boolean }[];
}

interface ChapterSummary {
  id: string;
  level: string;
  title: string;
  theme: string;
  cardCount: number;
}

interface ChapterDetail extends ChapterSummary {
  cards: CardItem[];
}

interface ProgressState {
  chapterId: string;
  knownCardIds: string[];
  practiceCardIds: string[];
}

interface ChapterStats {
  dueNow: number;
  totalCards: number;
  reviewedCards: number;
  avgStability: number;
  avgDifficulty: number;
}

interface ChaptersPageProps {
  token: string;
  chapters: ChapterSummary[];
  perChapterStats: Record<string, ChapterStats>;
  onStartReview: (chapterId: string) => void;
}

const API = '/api';

async function fetchChapter(id: string, token: string): Promise<ChapterDetail> {
  const [ch, prog] = await Promise.all([
    fetch(`${API}/chapters/${id}`, { headers: { Authorization: `Bearer ${token}` } }).then(r => r.json()),
    fetch(`${API}/progress/${id}`, { headers: { Authorization: `Bearer ${token}` } }).then(r => r.json()).catch(() => null),
  ]);
  return { ...ch, _progress: prog };
}

async function speakTts(cardId: string, token: string) {
  try {
    const res = await fetch(`${API}/tts/${cardId}`, { headers: { Authorization: `Bearer ${token}` } });
    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    new Audio(url).play().catch(() => {});
  } catch { /* silent */ }
}

/** Chapter list + detail panel. */
export function ChaptersPage({ token, chapters, perChapterStats, onStartReview }: ChaptersPageProps) {
  const [selectedId, setSelectedId] = React.useState<string | null>(chapters[0]?.id ?? null);
  const [detail, setDetail] = React.useState<ChapterDetail | null>(null);
  const [progress, setProgress] = React.useState<ProgressState | null>(null);
  const [loading, setLoading] = React.useState(false);
  const [search, setSearch] = React.useState('');

  React.useEffect(() => {
    if (!selectedId) return;
    setLoading(true);
    Promise.all([
      fetch(`${API}/chapters/${selectedId}`, { headers: { Authorization: `Bearer ${token}` } }).then(r => r.json()),
      fetch(`${API}/progress/${selectedId}`, { headers: { Authorization: `Bearer ${token}` } }).then(r => r.json()).catch(() => null),
    ])
      .then(([ch, prog]) => { setDetail(ch); setProgress(prog); })
      .catch(() => { setDetail(null); setProgress(null); })
      .finally(() => setLoading(false));
  }, [selectedId, token]);

  const filteredCards = detail?.cards.filter(c =>
    !search || c.word.toLowerCase().includes(search.toLowerCase()) || c.english.toLowerCase().includes(search.toLowerCase())
  ) ?? [];

  const knownIds = new Set(progress?.knownCardIds ?? []);
  const practiceIds = new Set(progress?.practiceCardIds ?? []);

  return (
    <div className="flex flex-col gap-4 px-4 py-6 max-w-5xl mx-auto w-full">
      <div>
        <h1 className="font-display text-2xl font-black text-foreground">Chapters</h1>
        <p className="text-sm text-muted-foreground mt-1">Browse and study vocabulary by chapter</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
        {chapters.map((ch, i) => {
          const st = perChapterStats[ch.id];
          const masteryPct = st ? (st.reviewedCards / Math.max(1, st.totalCards)) * 100 : 0;
          return (
            <motion.div
              key={ch.id}
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3, delay: i * 0.04, ease: [0.16, 1, 0.3, 1] }}
            >
              <ChapterCard
                id={ch.id}
                title={ch.title}
                theme={ch.theme}
                level={ch.level}
                wordCount={ch.cardCount}
                masteryPct={masteryPct}
                dueCount={st?.dueNow ?? 0}
                isSelected={selectedId === ch.id}
                onClick={() => setSelectedId(ch.id)}
              />
            </motion.div>
          );
        })}
      </div>

      {/* Chapter detail panel */}
      <AnimatePresence>
        {selectedId && (
          <motion.div
            key={selectedId}
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 24 }}
            transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
            className="rounded-3xl border-2 border-border bg-card p-6"
          >
            {loading ? (
              <div className="space-y-3">
                {[...Array(5)].map((_, i) => <div key={i} className="skeleton h-12 rounded-xl" />)}
              </div>
            ) : detail ? (
              <>
                <div className="flex items-start justify-between gap-4 mb-4">
                  <div>
                    <h2 className="font-display text-xl font-black text-foreground">{detail.title}</h2>
                    <p className="text-sm text-muted-foreground">{detail.theme} · {detail.cards.length} words</p>
                  </div>
                  <Button onClick={() => onStartReview(selectedId!)} size="sm">
                    Review →
                  </Button>
                </div>

                {/* Stats row */}
                {perChapterStats[selectedId] && (
                  <div className="grid grid-cols-3 gap-2 mb-4">
                    {[
                      { label: 'Due', val: perChapterStats[selectedId].dueNow, color: 'text-danger' },
                      { label: 'Known', val: knownIds.size, color: 'text-success' },
                      { label: 'Practicing', val: practiceIds.size, color: 'text-warning' },
                    ].map(({ label, val, color }) => (
                      <div key={label} className="rounded-xl bg-muted/50 p-2 text-center">
                        <p className={cn('font-display text-lg font-black', color)}>{val}</p>
                        <p className="text-xs text-muted-foreground">{label}</p>
                      </div>
                    ))}
                  </div>
                )}

                {/* Search */}
                <div className="relative mb-3">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" aria-hidden="true" />
                  <input
                    value={search}
                    onChange={e => setSearch(e.target.value)}
                    placeholder="Search words..."
                    className="w-full rounded-xl border-2 border-border bg-background pl-9 pr-9 py-2 text-sm focus:border-primary focus:outline-none transition-colors"
                    aria-label="Search words in this chapter"
                  />
                  {search && (
                    <button
                      onClick={() => setSearch('')}
                      className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                      aria-label="Clear search"
                    >
                      <X className="h-4 w-4" />
                    </button>
                  )}
                </div>

                {/* Word list */}
                <div className="max-h-80 overflow-y-auto space-y-1.5 pr-1" role="list" aria-label="Vocabulary list">
                  {filteredCards.length === 0 ? (
                    <p className="py-8 text-center text-sm text-muted-foreground">No words match your search.</p>
                  ) : (
                    filteredCards.map(card => {
                      const isKnown = knownIds.has(card.id);
                      const isPractice = practiceIds.has(card.id);
                      return (
                        <div
                          key={card.id}
                          role="listitem"
                          className="flex items-center gap-3 rounded-xl px-3 py-2.5 hover:bg-muted/50 transition-colors"
                        >
                          <span
                            className={cn(
                              'h-2.5 w-2.5 shrink-0 rounded-full',
                              isKnown ? 'bg-success' : isPractice ? 'bg-warning' : 'bg-muted-foreground/30',
                            )}
                            aria-label={isKnown ? 'Known' : isPractice ? 'Practicing' : 'New'}
                          />
                          <div className="min-w-0 flex-1">
                            <span className="font-bold text-sm">
                              {card.article && <span className="text-muted-foreground">{card.article} </span>}
                              {card.word}
                            </span>
                            <span className="mx-2 text-muted-foreground">·</span>
                            <span className="text-sm text-muted-foreground">{card.english}</span>
                          </div>
                          <button
                            onClick={() => speakTts(card.id, token)}
                            className="flex h-7 w-7 items-center justify-center rounded-lg text-muted-foreground hover:text-primary hover:bg-primary/10 transition-colors focus-ring"
                            aria-label={`Pronounce ${card.word}`}
                          >
                            <Volume2 className="h-3.5 w-3.5" />
                          </button>
                        </div>
                      );
                    })
                  )}
                </div>
              </>
            ) : (
              <EmptyState emoji="😕" title="Couldn't load chapter" description="Try selecting another chapter." />
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
