package com.example.flashcards.service;

import com.example.flashcards.entity.CardEntity;
import com.example.flashcards.entity.ChapterEntity;
import com.example.flashcards.model.Card;
import com.example.flashcards.model.Chapter;
import com.example.flashcards.model.ChapterSummary;
import com.example.flashcards.model.ExampleSentence;
import com.example.flashcards.repository.ChapterRepository;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.cache.annotation.Caching;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Comparator;
import java.util.List;
import java.util.NoSuchElementException;

@Service
public class ChapterService {
    private final ChapterRepository chapterRepository;
    private final ExampleSentenceService exampleSentenceService;

    public ChapterService(ChapterRepository chapterRepository, ExampleSentenceService exampleSentenceService) {
        this.chapterRepository = chapterRepository;
        this.exampleSentenceService = exampleSentenceService;
    }

    @Cacheable("chapter-summaries")
    @Transactional(readOnly = true)
    public List<ChapterSummary> getSummaries() {
        return chapterRepository.findAll().stream()
                .sorted(Comparator.comparing(ChapterEntity::getId))
                .map(chapter -> new ChapterSummary(
                        chapter.getId(),
                        chapter.getLevel(),
                        chapter.getTitle(),
                        chapter.getTheme(),
                        chapter.getCards().size()
                ))
                .toList();
    }

    @Cacheable(value = "chapters", key = "#chapterId")
    @Transactional
    public Chapter getChapter(String chapterId) {
        ChapterEntity chapter = chapterRepository.findById(chapterId)
                .orElseThrow(() -> new NoSuchElementException("Chapter not found: " + chapterId));
        exampleSentenceService.generateForChapter(chapter);
        return toDto(chapter);
    }

    private Chapter toDto(ChapterEntity chapter) {
        return new Chapter(
                chapter.getId(),
                chapter.getLevel(),
                chapter.getTitle(),
                chapter.getTheme(),
                chapter.getCards().stream().map(this::toDto).toList()
        );
    }

    @Caching(evict = {
        @CacheEvict(value = "chapters", key = "#result.id()"),
        @CacheEvict(value = "chapter-summaries", allEntries = true)
    })
    @Transactional
    public Chapter saveChapter(String level, String title, String theme, List<Card> cards) {
        String chapterId = slugify(level, title);

        // Delete existing chapter with same ID if re-uploading
        chapterRepository.deleteById(chapterId);
        chapterRepository.flush();

        ChapterEntity entity = new ChapterEntity();
        entity.setId(chapterId);
        entity.setLevel(level);
        entity.setTitle(title);
        entity.setTheme(theme);

        for (int i = 0; i < cards.size(); i++) {
            Card c = cards.get(i);
            CardEntity card = new CardEntity();
            card.setId(chapterId + "-" + (i + 1));
            card.setChapter(entity);
            card.setPosition(i + 1);
            card.setType(c.type() != null ? c.type() : "noun");
            card.setArticle(c.article());
            card.setWord(c.word());
            card.setEnglish(c.english());
            card.setHindi(c.hindi());
            entity.getCards().add(card);
        }

        chapterRepository.save(entity);
        exampleSentenceService.generateForChapter(entity);
        return toDto(entity);
    }

    @Caching(evict = {
        @CacheEvict(value = "chapters", key = "#chapterId"),
        @CacheEvict(value = "chapter-summaries", allEntries = true)
    })
    @Transactional
    public void deleteChapter(String chapterId) {
        if (!chapterRepository.existsById(chapterId)) {
            throw new NoSuchElementException("Chapter not found: " + chapterId);
        }
        chapterRepository.deleteById(chapterId);
    }

    private String slugify(String level, String title) {
        String raw = level + " " + title;
        return raw.toLowerCase()
                .replaceAll("[^a-z0-9]+", "-")
                .replaceAll("^-|-$", "");
    }

    private Card toDto(CardEntity card) {
        List<ExampleSentence> sentences = card.getExampleSentences().stream()
                .map(s -> new ExampleSentence(s.getId(), s.getSentenceDe(), s.getSentenceEn(), s.isAutoGenerated()))
                .toList();
        return new Card(
                card.getId(),
                card.getType(),
                card.getArticle(),
                card.getWord(),
                card.getEnglish(),
                card.getHindi(),
                sentences
        );
    }
}
