package com.example.flashcards.controller;

import com.example.flashcards.entity.CardEntity;
import com.example.flashcards.entity.ExampleSentenceEntity;
import com.example.flashcards.model.ExampleSentence;
import com.example.flashcards.model.ExampleSentenceRequest;
import com.example.flashcards.repository.CardRepository;
import com.example.flashcards.service.ExampleSentenceService;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.NoSuchElementException;

@RestController
@RequestMapping("/api/admin/cards")
public class SentenceController {

    private final ExampleSentenceService sentenceService;
    private final CardRepository cardRepository;

    public SentenceController(ExampleSentenceService sentenceService, CardRepository cardRepository) {
        this.sentenceService = sentenceService;
        this.cardRepository = cardRepository;
    }

    @PostMapping("/{cardId}/sentences")
    public ExampleSentence addSentence(@PathVariable String cardId,
                                       @Valid @RequestBody ExampleSentenceRequest request) {
        CardEntity card = cardRepository.findById(cardId)
                .orElseThrow(() -> new NoSuchElementException("Card not found: " + cardId));
        ExampleSentenceEntity entity = sentenceService.addSentence(cardId, request.sentenceDe(), request.sentenceEn(), card);
        return toDto(entity);
    }

    @PutMapping("/{cardId}/sentences/{id}")
    public ExampleSentence updateSentence(@PathVariable String cardId,
                                          @PathVariable String id,
                                          @Valid @RequestBody ExampleSentenceRequest request) {
        ExampleSentenceEntity entity = sentenceService.updateSentence(id, request.sentenceDe(), request.sentenceEn());
        return toDto(entity);
    }

    @DeleteMapping("/{cardId}/sentences/{id}")
    public ResponseEntity<Void> deleteSentence(@PathVariable String cardId,
                                                @PathVariable String id) {
        sentenceService.deleteSentence(id);
        return ResponseEntity.noContent().build();
    }

    private ExampleSentence toDto(ExampleSentenceEntity entity) {
        return new ExampleSentence(entity.getId(), entity.getSentenceDe(), entity.getSentenceEn(), entity.isAutoGenerated());
    }

    @org.springframework.web.bind.annotation.ExceptionHandler(NoSuchElementException.class)
    public ResponseEntity<Void> handleNotFound(NoSuchElementException e) {
        return ResponseEntity.notFound().build();
    }
}
